### ISSUE TITLE
Make Resources screen slide up from below

### ISSUE THREAD

**Issue by abi** [jeff-da/expo-harvard-cs50#12]
and not have StackNavigation behavior

**Comment by jeff-da** [comment]
it does this already on Android

**Comment by abi** [comment]
Yeah, convention for StackNavigation is left-to-right on iOS and bottom-up on Android. I want Resources Screen to do this transition: https://developer.apple.com/documentation/uikit/uimodaltransitionstyle/1621455-coververtical on iOS and correct corresponding transition on Android.
